### ISSUE TITLE
建议增加目录

### ISSUE THREAD

**Issue by AlgerFan** [adlered/sakura-for-bolo-and-solo#1]
皮肤很喜欢，但非常建议增加目录，文章长了就难受了，离不开了🤣🤣

**Comment by AlgerFan** [comment]
再说一下，markdown渲染的也很棒👍👍

**Comment by adlered** [comment]
前两天加上了，没来得及推

**Comment by adlered** [comment]
已更新 [#972a786](https://github.com/adlered/sakura-for-bolo-and-solo/commit/972a786e19b362a10ddeab9b253f4c4934bfc312)
