### ISSUE TITLE
评论样式错乱

### ISSUE THREAD

**Issue by AlgerFan** [adlered/sakura-for-bolo-and-solo#2]
solo版本 3.9.0，使用的是外挂皮肤，详见：[Blog](https://www.algerfan.cn/?skin=solo-sakura)
![image](https://user-images.githubusercontent.com/38367204/78159868-be3ebe00-7475-11ea-8630-57bc15d5857e.png)

**Comment by adlered** [comment]
确实出问题了，但是别的博客貌似没有这个问题，加我QQ吧，1101635162，我诊断一下

**Comment by adlered** [comment]
经 Solo 4.0.0 测试没有问题，请更新到 4.0.0 后重试
![image.png](https://pic.stackoverflow.wiki/uploadImages/218/246/109/28/2020/04/02/16/26/fd574330-5d7a-498b-b997-7f4cf5646d75.png)

**Comment by AlgerFan** [comment]
好的
